---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-mysqlbk-bk-io-v1-backupcrd
  failurePolicy: Fail
  name: mbackupcrd.kb.io
  rules:
  - apiGroups:
    - mysqlbk.bk.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupcrds
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mysqlbk-bk-io-v1-backupcrd
  failurePolicy: Fail
  name: vbackupcrd.kb.io
  rules:
  - apiGroups:
    - mysqlbk.bk.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupcrds
  sideEffects: None
