# permissions for end users to view backupcrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: backupcrd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mysqlbackup
    app.kubernetes.io/part-of: mysqlbackup
    app.kubernetes.io/managed-by: kustomize
  name: backupcrd-viewer-role
rules:
- apiGroups:
  - mysqlbk.bk.io
  resources:
  - backupcrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysqlbk.bk.io
  resources:
  - backupcrds/status
  verbs:
  - get
