---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mysqlbk.bk.io
  resources:
  - backupcrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysqlbk.bk.io
  resources:
  - backupcrds/finalizers
  verbs:
  - update
- apiGroups:
  - mysqlbk.bk.io
  resources:
  - backupcrds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - batch
  resources:
    - jobs/status
  verbs:
    - get
