apiVersion: v1
kind: Service
metadata:
  name: {{.ObjectMeta.Name}}-svc
  namespace: {{.ObjectMeta.Namespace}}
spec:
  selector:
    app: {{.ObjectMeta.Name}}-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
