apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.ObjectMeta.Name}}-pvc
  namespace: {{.ObjectMeta.Namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
