apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.ObjectMeta.Name}}-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.3.23 
    path: "/k8s/volume/mysqlbak"
